---
- name: Ensure domain directories are present.
  file:
    name: "{{ dehydrated_certs_dir }}/{{ item.name }}"
    state: directory
  with_items: "{{ dehydrated_domains }}"

- name: Render hook script templates.
  template:
    src: hook.sh.j2
    dest: "{{ dehydrated_certs_dir }}/{{ item.name }}/hook.sh"
  with_items: "{{ dehydrated_domains }}"

- name: Ensure Domains are in domains.txt
  lineinfile:
    path: "{{ dehydrated_config_dir }}/domains.txt"
    line: "{{ item.name }}{% if 'alternate_names' in item %}{% for an in item.alternate_names %} {{ an|default(omit) }}{% endfor %}{% endif %}"
  with_items: "{{ dehydrated_domains }}"
  notify: dehydrated run