---
- name: Ensure domain directories are present.
  ansible.builtin.file:
    name: "{{ dehydrated_certs_dir }}/{{ item.name }}"
    state: directory
  with_items: "{{ dehydrated_domains }}"

- name: Render hook script templates.
  ansible.builtin.template:
    src: hook.sh.j2
    dest: "{{ dehydrated_certs_dir }}/{{ item.name }}/hook.sh"
    mode: '755'
  with_items: "{{ dehydrated_domains }}"

- name: Add configuration to call hook scripts
  ansible.builtin.lineinfile:
    path: "{{ dehydrated_certs_dir }}/{{ item.name }}/config"
    regexp: "^HOOK="
    line: "HOOK={{ dehydrated_certs_dir }}/{{ item.name }}/hook.sh"
    create: true
  with_items: "{{ dehydrated_domains }}"

- name: Ensure Domains are in domains.txt
  ansible.builtin.template:
    src: domains.txt.j2
    dest: "{{ dehydrated_config_dir }}/domains.txt"
  notify: dehydrated run
