---
- name: Dehydrated register
  ansible.builtin.command: "{{ dehydrated_binary }} --register --accept-terms"

- name: Dehydrated run
  ansible.builtin.command: "{{ dehydrated_binary }} --cron"
  when: dehydrated_force_update|default(False)|bool
